### ISSUE TITLE
Avoid error for sources with no organization

### ISSUE THREAD

**Issue by avdata99** [GSA/ckanext-datagovcatalog#16]
If we try to send notifications for a no-organization source after a harvest job finished, we will have [an error](https://app.circleci.com/pipelines/github/GSA/ckanext-datajson/197/workflows/27bc1297-c6f7-4a93-bd37-cd06e85183df/jobs/997)

Now, [the organization is required](https://github.com/GSA/ckanext-datagovcatalog/blob/master/ckanext/datagovcatalog/harvester/notifications.py#L37). 

# Tasks
 - [x] Allow process the chained action`harvest_get_notifications_recipients` without error if organization not exists
 - [x] Ensure to return at least the base recipient list (and fix [the previous empty results](https://github.com/GSA/ckanext-datagovcatalog/blob/master/ckanext/datagovcatalog/harvester/notifications.py#L32))
 - [x] Add a test case
 - [x] Use the canonical script to test this extension
